### ISSUE TITLE
Is Github version up-to-date?

### ISSUE THREAD

**Issue by rinigus** [martonmiklos/sailfishos-presage-predictor#10]
Looks like version in Github is not the latest. At OpenRepos, you have 1.0-7, while sources here are for 1.0-4. Would you mind to update the sources here?

**Comment by rinigus** [comment]
This is a reminder asking you to upload latest version of the plugin. At Github, we have latest commit https://github.com/martonmiklos/sailfishos-presage-predictor/commit/c4e32ff00af126bc04605a24dd2ab18ae917db1a from Dec 8 and RPM SPEC for version 1.0.-4

At OpenRepos, version is 1.0-7 from Dec 13.

In addition to performance, I would like to work on other issues as well that require latest plugin / libpresage versions. Presage seems is all uploaded, plugin is missing :)

Or were 1.0-4 and -7 identical and only presage part was changed?

**Comment by martonmiklos** [comment]
I have added a feature to separate the user database per language.

I think I have pushed everything what I have had locally know so it should be safe to start working on it.

**Comment by rinigus** [comment]
Great! I will do so.

As for locale changes, it looks to be the bug of tinyXML used by presage. Unfortunately, tinyXML is not developed anymore (from 2011). I plan to convert it to tinyXML2, as suggested by tinyXML author. That should resolve locale problem.
