### ISSUE TITLE
Packaging: naming convention

### ISSUE THREAD

**Issue by rinigus** [martonmiklos/sailfishos-presage-predictor#18]
There are several packages that are installed to get Presage text prediction on device. Would be good to review the names and agree on them.

As now SFOS plugin is compiled statically with presage library, we need on device:

* plugin 
* presage-data (contains default config + empty databases to keep presage happy on start)
* presage language packages (en, hu, se, et, ...)
* presage supporting keyboards

There is no need to install libpresage anymore.

I personally find current name of plugin confusing and would suggest to start using `maliit-plugin-presage` instead.

As for language packs, we could use `presage-data-XX` or `presage-lang-XX`. Having _lang_ in the name makes it clear on what it is, but probably data is OK as well. Thoughts?

As for keyboards, they seem to be fine for me as they are (arrowboard-sv-presage, for example).

Your thoughts about it? @martonmiklos  and @ljo

I am writing scripts for language packaging to support new MARISA format allowing you to test it.

**Comment by martonmiklos** [comment]
I have just checked how Jolla named their XT9 plugin and:
```
[root@Sailfish nemo]# zypper se xt9
Loading repository data...
Reading installed packages...

S | Name                  | Summary                                 | Type   
--+-----------------------+-----------------------------------------+--------
i | feature-xt9           | Feature for supporting xt9              | package
i | jolla-xt9             | Jolla Xt9 integration                   | package
i | jolla-xt9-cp          | Jolla Xt9 China integration             | package
  | patterns-sailfish-xt9 | Pattern for XT9 support for Sailfish OS | package
```
For me it is on the same unmeaningfulness level with the presage_predictor, so I am fine with using `maliit-plugin-presage`.

Regarding to the data packages: I was thinking about getting rid of them. Statically compiled in XML config shall fit our needs once the user configuration get implemented. 

Language pack naming convention is also fine from my side.

**Comment by rinigus** [comment]
Thanks for checking xt9 - don't own any official device and can't access them :)

Agreed, we can join empty databases and static config into  maliit-plugin-presage, if I understood your suggestion right.

**Comment by martonmiklos** [comment]
Correct. I would suggest to have only have one plugin package and a lang specific package. (And the keyboards of course.)

**Comment by rinigus** [comment]
Closing since Marisa PR fixed it
