### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by rinigus** [martonmiklos/sailfishos-presage-predictor#3]
Congratulations on the release, I am looking forward to test it! It looks that the license of your code is missing in the repository. Would you mind to add it? Seems that Presage is distributed under GPL, according to their home page.

**Comment by martonmiklos** [comment]
I have added a GNU General Public License v3.0 license to the project, I hope this is going to be comfortable to anyone.

**Comment by rinigus** [comment]
Thank you very much! Its surely fine for ported devices and normal users. If some company wants to release it as a part of their product, they can always ask you, as a copyright owner, to make a special version for them with the other license.
