### ISSUE TITLE
Performance degradation on 4.2.0.21

### ISSUE THREAD

**Issue by rinigus** [martonmiklos/sailfishos-presage-predictor#33]
With the reflash using 4.2.0.21, I have seen rather poor predictions by the keyboard. Not sure what is going on, will have to check the logs and installed packages. Could be also some issue with my setup. Recording as an issue here to keep track.

Lang: en_US
Packages installed from Chum and OpenRepos

**Comment by martonmiklos** [comment]
I just realised this for hu_HU so looks to be not locale dependant.
HW: XA2

**Comment by rinigus** [comment]
Looking into it. Have to remember how we made it all happen first :)

**Comment by rinigus** [comment]
Issue is in language code setting:

```QML
    PresagePredictor {
        id: thread
        // note: also china language codes being set with this, assume xt9 model just ignores such
        language: layoutRow.layout ? layoutRow.layout.languageCode : ""
```
There is no `layoutRow` anymore in SFOS 4.2. So, we need new way to set language code.

/cc @pvuorela

**Comment by rinigus** [comment]
Don't know whether it is a perfect and expected solution for SFOS 4.2 - submitted PR for review #34.
