### ISSUE TITLE
Long  tap on a suggestion should bring up a menu with a forgot word action

### ISSUE THREAD

**Issue by martonmiklos** [martonmiklos/sailfishos-presage-predictor#6]
Sometimes misspelled words got learned it would be great to allow the users to get rid of them.
This needs some work on the QML, the plugin and on the presage itself.

**Comment by rinigus** [comment]
Just to let you know: I have started working on this, from Presage side.

**Comment by rinigus** [comment]
I am getting close to finishing work on this. There is a corner case I have to take care of, but it should be done tonight. At present, I have forget action associated with Press and Hold action, no additional menu. That actually seems to work quite nicely, without additional menu to click.

I'll submit it on top of Hunspell PR.

**Comment by rinigus** [comment]
The keyboard plugin with "forget" functionality is ready for submission. I would need hunspell to be approved though, first.
