### ISSUE TITLE
Predictions using async API

### ISSUE THREAD

**Issue by rinigus** [martonmiklos/sailfishos-presage-predictor#9]
I have started looking into presage, into it's internals and performance. There is a lot it has to do to get predictions and while I do have ideas on how to make it faster, I suggest to make predictions in separate thread. Namely, QML interface would add changes in context, keyboard processing as it has now, but would get prediction via signal (or just notified via signal that prediction changed). 

Such approach would allow us to later use more advanced language models, additional predictors and keep fast response of the keyboard .

**Comment by rinigus** [comment]
We could use approaches suggested at https://forum.qt.io/topic/15988/how-to-cancel-pending-unprocessed-emitted-signals to process only latest available context by presage worker thread. Since separate thread would use queued signals, that should be rather simple .

**Comment by martonmiklos** [comment]
Yes I have been thinking about the same previously.

**Comment by rinigus** [comment]
Adding link to the issue where I will try to improve the performance of presage: https://github.com/rinigus/presage/issues/1

**Comment by rinigus** [comment]
Hi! I'll start to work on this one on the top of Marisa PR. It shouldn't take long to fix it.

**Comment by martonmiklos** [comment]
Sounds good!
